### ISSUE TITLE
AttributeError: 'str' object has no attribute 'datset'

### ISSUE THREAD

**Issue by marsggbo** [carpedm20/ENAS-pytorch#27]
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    main(args)
  File "main.py", line 26, in main
    dataset = data.image.Image(args.data_path)
  File "/home/comp/csxinhe/Code/ENAS-pytorch/data/image.py", line 8, in __init__
    if args.datset == 'cifar10':
AttributeError: 'str' object has no attribute 'datset'

**Comment by favorxin** [comment]
@marsggbo Do you handle this problem? I met it, too.

**Comment by zmsunnyday** [comment]
I think this is a bug. I fixed it by remove all the if-else in data.image.Image.__init__, and the code run normally

**Comment by ZTao-z** [comment]
I fixed it by change the value of the function parameter

（1） File "main.py", line 26
dataset = data.image.Image(args.data_path)
change into:
dataset = data.image.Image(args)

（2）File "/data/image.py", line 8
if args.datset == 'cifar10':
change into:
if args.datset == 'cifar':

**Comment by ZTao-z** [comment]
I fixed it by change the value of the function parameter

（1） File "main.py", line 26
dataset = data.image.Image(args.data_path)
change into:
dataset = data.image.Image(args)

（2）File "/data/image.py", line 8
if args.dataset == 'cifar10':
change into:
if args.dataset == 'cifar':

**Comment by kukby** [comment]
@ZTao-z  I try this method. But when i change dataset = data.image.Image(args.data_path) into dataset = data.image.Image(args). I meet a problem
AttributeError: 'Namespace' object has no attribute 'num_workers'
Do you have meet this problem when you change the value?

**Comment by SuperRui41** [comment]
> @ZTao-z I try this method. But when i change dataset = data.image.Image(args.data_path) into dataset = data.image.Image(args). I meet a problem
> AttributeError: 'Namespace' object has no attribute 'num_workers'
> Do you have meet this problem when you change the value?

My situation is the same as yours. How did you solve this problem in the end?
