### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'num_workers'

### ISSUE THREAD

**Issue by kukby** [carpedm20/ENAS-pytorch#51]
kukby@kukby-GI5KN54:~/ENAS-pytorch-master$ python3 main.py --network_type cnn --dataset cifar --controller_optim momentum --controller_lr_cosine=True                --controller_lr_max 0.05 --controller_lr_min 0.0001 --entropy_coeff 0.1
2020-03-03 20:59:42,792:INFO::[*] Make directories : logs/cifar_2020-03-03_20-59-42
Files already downloaded and verified
Traceback (most recent call last):
  File "main.py", line 54, in <module>
    main(args)
  File "main.py", line 26, in main
    dataset = data.image.Image(args)
  File "/home/kukby/ENAS-pytorch-master/data/image.py", line 30, in __init__
    num_workers=args.num_workers, pin_memory=True)

**Comment by Javen-Van** [comment]
Hi, have you handle this problem? I met it, too
