### ISSUE TITLE
RuntimeError: saved_forINTERNAL ASSERT FAILED at

### ISSUE THREAD

**Issue by Shn9909** [carpedm20/ENAS-pytorch#57]
I encountered this strange error. Here is the output, thank you.

Traceback (most recent call last):
  File "D:/xiangmu/ENAS-pytorch-master/main.py", line 56, in <module>
    main(args)
  File "D:/xiangmu/ENAS-pytorch-master/main.py", line 35, in main
    trnr.train()
  File "D:\xiangmu\ENAS-pytorch-master\trainer.py", line 223, in train
    self.train_shared(dag=dag)
  File "D:\xiangmu\ENAS-pytorch-master\trainer.py", line 314, in train_shared
    loss.backward()
  File "C:\Users\sunhaonan\.conda\envs\enas\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\sunhaonan\.conda\envs\enas\lib\site-packages\torch\autograd\__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: saved_forINTERNAL ASSERT FAILED at "..\\torch\\csrc\\autograd\\saved_variable.cpp":133, please report a bug to PyTorch. No grad_fn for non-leaf saved tensor

**Comment by Gangle-Sun** [comment]
how do you solve this problem? I meet the same error
