### ISSUE TITLE
RuntimeError: cuda runtime error (59) : device-side assert triggered

### ISSUE THREAD

**Issue by karandwivedi42** [carpedm20/ENAS-pytorch#7]
Running with the default settings on 1 GPU leads to this error after running successfully for a lot of epochs. (both wikitext and ptb)

```
train_shared| loss: 2.844:  11%|███████▏                                                           | 3500/32634 [00:40<05:19, 91.09it/s]
2018-03-07 05:26:19,885:INFO::| epoch  83 | lr 1.20 | loss 2.97 | ppl    19.43
train_shared| loss: 2.750:  16%|██████████▊                                                        | 5250/32634 [00:59<04:58, 91.77it/s]
2018-03-07 05:26:39,208:INFO::| epoch  83 | lr 1.20 | loss 2.87 | ppl    17.70
train_shared| loss: 2.619:  21%|██████████████▎                                                    | 7000/32634 [01:19<05:03, 84.33it/s]
2018-03-07 05:26:58,999:INFO::| epoch  83 | lr 1.20 | loss 2.95 | ppl    19.18
train_shared| loss: 2.627:  27%|█████████████████▉                                                 | 8750/32634 [01:38<04:20, 91.85it/s]
2018-03-07 05:27:18,144:INFO::| epoch  83 | lr 1.20 | loss 3.26 | ppl    25.94
train_shared| loss: 4.249:  32%|█████████████████████▏                                            | 10500/32634 [01:57<04:00, 91.96it/s]
2018-03-07 05:27:37,222:INFO::| epoch  83 | lr 1.20 | loss 2.93 | ppl    18.67
train_shared| loss: 2.546:  38%|████████████████████████▊                                         | 12250/32634 [02:17<04:00, 84.66it/s]
2018-03-07 05:27:56,890:INFO::| epoch  83 | lr 1.20 | loss 2.96 | ppl    19.35
train_shared| loss:   nan:  43%|████████████████████████████▎                                     | 14000/32634 [02:37<03:35, 86.57it/s]
2018-03-07 05:28:17,371:INFO::| epoch  83 | lr 1.20 | loss nan | ppl      nan
train_shared| loss:   nan:  43%|████████████████████████████▍                                     | 14035/32634 [02:37<03:34, 86.72it/sT
HCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/THCTensorCopy.cu line=100 error=59 : device-side asse
rt triggered
Traceback (most recent call last):
  File "main.py", line 45, in <module>
    main(args)
  File "main.py", line 34, in main
    trainer.train()
  File "/home/karan/metalearning-project/ENAS-pytorch/trainer.py", line 94, in train
    self.train_controller()
  File "/home/karan/metalearning-project/ENAS-pytorch/trainer.py", line 225, in train_controller
    dags, log_probs, entropies = self.controller.sample(with_details=True)
  File "/home/karan/metalearning-project/ENAS-pytorch/models/controller.py", line 96, in sample
    is_embed=block_idx==0)
  File "/home/karan/metalearning-project/ENAS-pytorch/models/controller.py", line 67, in forward
    logits = self.decoders[block_idx](hx)
  File "/home/karan/anaconda2/envs/torch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/karan/anaconda2/envs/torch/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 55, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/karan/anaconda2/envs/torch/lib/python3.6/site-packages/torch/nn/functional.py", line 835, in linear
    return torch.addmm(bias, input, weight.t())
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/TH
CTensorCopy.cu:100
/opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/THCTensorRandom.cuh:179: void sampleMultinomialOnce(long *, long, int, T *
, T *) [with T = float, AccT = float]: block: [0,0,0], thread: [0,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
/opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/THCTensorRandom.cuh:179: void sampleMultinomialOnce(long *, long, int, T *
, T *) [with T = float, AccT = float]: block: [0,0,0], thread: [1,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
/opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/THCTensorRandom.cuh:179: void sampleMultinomialOnce(long *, long, int, T *
, T *) [with T = float, AccT = float]: block: [0,0,0], thread: [2,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
/opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/THCTensorRandom.cuh:179: void sampleMultinomialOnce(long *, long, int, T *
, T *) [with T = float, AccT = float]: block: [0,0,0], thread: [3,0,0] Assertion `THCNumerics<T>::ge(val, zero)` failed.
```

**Comment by karandwivedi42** [comment]
Might be related to https://github.com/pytorch/pytorch/issues/1010

**Comment by dukebw** [comment]
See my answer to #6.

**Comment by karandwivedi42** [comment]
Thanks! I will try that.

**Comment by shisi2015** [comment]
is this error solved and how?
